name:base

on:Cli
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:'name:push on:'runs-on:jobs'build:'''

    runs-on: Cli'ubuntu-latest:run'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name:'[]'
      run: >
        sudo apt-get update && 
        sudo apt-get install gnat gprbuild

    - name: Build'Base:run'
      run: gprbuild -j0 -p
